#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(local_size_x_id = 1) in;
layout(std430, binding = 0) buffer lay1 //Input
{ 
	float invar[];
};

layout(std430, binding = 1) buffer lay0 //Output
{ 
	float outvar[];
}; 

layout(binding = 2) uniform UBO {
	float value;
	float value2;
} UFV;

void main() 
{
  if(gl_GlobalInvocationID.x >= 5)
	return;
	outvar[gl_GlobalInvocationID.x] = (invar[gl_GlobalInvocationID.x] + UFV.value) * UFV.value2;
}